config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount API::Base, at: "/"
  get 'stripes/new'
  # post 'create_cart', to: 'carts#create', as: "create_cart"
  # get 'show/cart', to: 'carts#show', as: "show"
  get 'indentification/identification'
  devise_for :traders, controllers: { registrations: 'registrations' }
  devise_for :users, controllers: { registrations: 'registrations' }

  root to: 'stores#index'

  get '/orders', to: 'orders#orders', as: :orders
  get '/history', to: 'orders#history', as: :history
  get '/user_show', to: 'orders#user_show', as: :user_show
  get '/dashboard', to: 'orders#dashboard', as: :dashboard
  post '/order_update', to: 'orders#validation_order', as: :validation_order

  get '/trader_show/:store_id', to: 'stores#trader_show', as: :trader_show
  get '/home', to: 'stores#home', as: :home

  resources :stores do
    resources :products, only: %i[index new create]
  end
  resources :products, only: %i[show edit update destroy]

  resources :carts, only: %i[index create destroy]
  patch '/update_cart' => 'carts#update', as: 'update_cart'

  scope '/checkouts' do
    get 'create/:store_id', to: 'checkouts#create_checkout'
    get 'cancel', to: 'checkouts#cancel', as: 'checkout_cancel'
    get 'success/:store_id', to: 'checkouts#success', as: 'checkout_success'
    get 'checkout', to: 'checkouts#checkout', as: 'checkout'
  end

  get '/identification' => 'identifications#identification', as: :identification
  get '/trader_person' => 'identifications#trader_person', as: :trader_person

  get '/trader_edit' => 'identifications#trader_edit', as: :trader_edit
  post '/trader_update' => 'identifications#trader_update', as: :trader_update

  get '/info' => 'identifications#info_stripe', as: :info
  post '/user_info' => 'identifications#user_info', as: :user_info

  get '/trader_info' => 'identifications#trader_info', as: :trader_info
  post '/trader_info_create' => 'identifications#trader_info_create', as: :trader_info_create

  get '/index_sub' => 'subscriptions#index', as: :index_sub
  post '/checkout_sub' => 'subscriptions#checkout_sub', as: :checkout_sub
  post '/webhook' => 'subscriptions#webhook', as: :webhook
  get '/delete_sub' => 'subscriptions#delete_sub', as: :delete_sub
  get '/success' => 'subscriptions#success', as: :success
  get '/checkout_session' => 'subscriptions#checkout_session', as: :checkout_session
end

app/models/store.rb
# frozen_string_literal: true

class Store < ApplicationRecord
  has_one_attached :photos
  validates :photos, presence: true
  belongs_to :trader
  has_many :products, dependent: :destroy
  has_many :orders

  searchkick

  def store_photo
    photos.key
  end
end

app/controllers/api/v1/stores.rb
module API
  module V1
    class Stores < Grape::API
      include API::V1::Defaults
      resource :stores do
        desc "Return all stores"
        get "" do
          Store.all
        end
      desc "Return a store"
        params do
          requires :id, type: String, desc: "ID of the store"
        end
        get ":id" do
          User.where(id: permitted_params[:id]).first!
        end
      end
    end
  end
end

app/controllers/stores_controller.rb
# frozen_string_literal: true

class StoresController < ApplicationController

  def home

  end
  
  def index
    @stores = if params['search'].present?
                Store.includes([photos_attachment: :blob]).find(params['search']['query'])
              else
                Store.all.includes([photos_attachment: :blob])
              end
  end

  def show
    @store = Store.find(params[:id])
    @products = @store.products.includes([photos_attachments: :blob])
    @cart = Cart.new
  end

  def trader_show
    @store = Store.find(current_trader.store.id)
    # @cart = Cart.new
  end

  def new
    @store = Store.new
  end

  def create
    @store = Store.create(store_params)
    @store.trader = Trader.find(current_trader.id)
    # CreateSubscription.new(current_trader).call
    if @store.save
      redirect_to store_path(@store)
    else
      render action: 'index'
    end
  end

  def edit
    @store = Store.find(params[:id])
  end

  def update
    @store = Store.find(params[:id])
    store_data = store_params

    Cloudinary::Uploader.destroy(@store.photos.key) if store_params['photos'].nil? == false
    UpdateStoreService.new(params[:id], store_data).call
    redirect_to store_path(params[:id])
  end

  private

  def store_params
    params.require(:store).permit(:presentation, :name, :photos)
  end
end

app/helpers/stores_helper.rb
# frozen_string_literal: true

module StoresHelper
end

app/views/stores/_edit.html.erb
<%= render "shared/form" %>

app/views/stores/_new.html.erb
<%= render "shared/form" %>

app/views/stores/_trader_show.html.erb
<div class="container">
<% @store.products.each do |product| %>
      <div class="card-product">
    <%= link_to controller: "products", :class => "photo_product", action: "edit", id: product, :remote => true  do %>
          <div>
            <%= cl_image_tag(product.first_product_photo, :width => 250, :height => 200) if product.product_photo_present? %>
          </div>
          <div class="card-product-infos">
            <h2><%= product.name %></h2>
            <p><%= product.presentation %></p>
          </div>
    <% end %>
          <div class="card-trip-pricing">
            <h2><%= product.price %> € </h2>
            <%= button_to "Ajouter au panier", carts_path(cart: {product_id: product.id, store_id: product.store_id, quantity: 1}), :method => :post, class: "btn btn-success"%>
          </div>
          <div class="delete_product">
            <% if current_trader == @store.trader %>
              <%= link_to "Suprimer", product_path(product), :method => :delete,class: "btn btn-light card-trip-user avatar-bordered", :data => {:confirm => 'Are you sure?'} %>
            <% end %>
          </div>
      </div>
  <% end %>
</div>

app/views/stores/edit.html.erb
edit.html.erb
<%= render "shared/form" %>

app/views/stores/edit.js.erb
a = document.querySelector('#dashboard_partial')
a.innerHTML = "";
a.insertAdjacentHTML('beforeend',"<%= escape_javascript render 'stores/edit', locals: {:store => @store } %>");

app/views/stores/home.html.erb
<h1>toto</h1>
<%= render "shared/carousel" %>

app/views/stores/index.html.erb
<div class="store_index">
  <div class="cards" id="cards_index">
      <% if @stores.present? %>
        <% @stores.each do |store|  %>
          <a href = "stores/<%= store.id %>">
            <div class="card-trip">
              <%= cl_image_tag store.store_photo if store.photo_present? %>
              <div class="card-store-infos">
                <div>
                  <h2><%= store.name.html_safe %></h2>
                  <p><%= store.presentation.html_safe %></p>
                </div>
                <h2 class="card-trip-pricing"></h2>
              </div>
            </div>
          </a>
        <% end %>
      <% end %>
  </div>
</div>

app/views/stores/new.html.erb
<h1>new store</h1>
<%= render "shared/form" %>

app/views/stores/new.js.erb
a = document.querySelector('#dashboard_partial')
a.innerHTML = "";
a.insertAdjacentHTML('beforeend',"<%= escape_javascript render 'stores/new', locals: {:store => @store } %>");

app/views/stores/show.html.erb
<div class="container">
  <% @products.each do |product| %>
      <div class="card-product">
    <%= link_to controller: "products", :class => "photo_product", action: "show",id: product, store_id: product.id do %>
          <div class="show_photo_store">
              <%= cl_image_tag(product.first_product_photo, :width => 250, :height => 200) if product.photo_present? %>
          </div>
          <div class="card-product-infos">
            <h2><%= product.name %></h2>
            <p><%= simple_format(product.presentation) %></p>
          </div>
    <% end %>
          <div class="card-trip-pricing">
            <h2><%= product.price %> € </h2>
            <%= button_to "Ajouter au panier", carts_path(cart: {product_id: product.id, store_id: product.store_id, quantity: 1}), :method => :post, class: "btn btn-success"%>
          </div>
      </div>
  <% end %>
</div>

app/views/stores/trader_show.js.erb
a = document.querySelector('#dashboard_partial')
a.innerHTML = "";
a.insertAdjacentHTML('beforeend',"<%= escape_javascript render 'stores/trader_show', locals: {:store => @store } %>");