config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount API::Base, at: "/"
  get 'stripes/new'
  # post 'create_cart', to: 'carts#create', as: "create_cart"
  # get 'show/cart', to: 'carts#show', as: "show"
  get 'indentification/identification'
  devise_for :traders, controllers: { registrations: 'registrations' }
  devise_for :users, controllers: { registrations: 'registrations' }

  root to: 'stores#index'

  get '/orders', to: 'orders#orders', as: :orders
  get '/history', to: 'orders#history', as: :history
  get '/user_show', to: 'orders#user_show', as: :user_show
  get '/dashboard', to: 'orders#dashboard', as: :dashboard
  post '/order_update', to: 'orders#validation_order', as: :validation_order

  get '/trader_show/:store_id', to: 'stores#trader_show', as: :trader_show
  get '/home', to: 'stores#home', as: :home

  resources :stores do
    resources :products, only: %i[index new create]
  end
  resources :products, only: %i[show edit update destroy]

  resources :carts, only: %i[index create destroy]
  patch '/update_cart' => 'carts#update', as: 'update_cart'

  scope '/checkouts' do
    get 'create/:store_id', to: 'checkouts#create_checkout'
    get 'cancel', to: 'checkouts#cancel', as: 'checkout_cancel'
    get 'success/:store_id', to: 'checkouts#success', as: 'checkout_success'
    get 'checkout', to: 'checkouts#checkout', as: 'checkout'
  end

  get '/identification' => 'identifications#identification', as: :identification
  get '/trader_person' => 'identifications#trader_person', as: :trader_person

  get '/trader_edit' => 'identifications#trader_edit', as: :trader_edit
  post '/trader_update' => 'identifications#trader_update', as: :trader_update

  get '/info' => 'identifications#info_stripe', as: :info
  post '/user_info' => 'identifications#user_info', as: :user_info

  get '/trader_info' => 'identifications#trader_info', as: :trader_info
  post '/trader_info_create' => 'identifications#trader_info_create', as: :trader_info_create

  get '/index_sub' => 'subscriptions#index', as: :index_sub
  post '/checkout_sub' => 'subscriptions#checkout_sub', as: :checkout_sub
  post '/webhook' => 'subscriptions#webhook', as: :webhook
  get '/delete_sub' => 'subscriptions#delete_sub', as: :delete_sub
  get '/success' => 'subscriptions#success', as: :success
  get '/checkout_session' => 'subscriptions#checkout_session', as: :checkout_session
end

app/views/shared/_carousel.html.erb
<h1>CSS-only Carousel</h1>

<p>This carousel is created with HTML and CSS only.</p>

<section class="carousel" aria-label="Gallery">
  <ol class="carousel__viewport">
    <li id="carousel__slide1"
        tabindex="0"
        class="carousel__slide">
      <div class="carousel__snapper">
        <a href="#carousel__slide4"
           class="carousel__prev">Go to last slide</a>
        <a href="#carousel__slide2"
           class="carousel__next">Go to next slide</a>
      </div>
    </li>
    <li id="carousel__slide2"
        tabindex="0"
        class="carousel__slide">
      <div class="carousel__snapper"></div>
      <a href="#carousel__slide1"
         class="carousel__prev">Go to previous slide</a>
      <a href="#carousel__slide3"
         class="carousel__next">Go to next slide</a>
    </li>
    <li id="carousel__slide3"
        tabindex="0"
        class="carousel__slide">
      <div class="carousel__snapper"></div>
      <a href="#carousel__slide2"
         class="carousel__prev">Go to previous slide</a>
      <a href="#carousel__slide4"
         class="carousel__next">Go to next slide</a>
    </li>
    <li id="carousel__slide4"
        tabindex="0"
        class="carousel__slide">
      <div class="carousel__snapper"></div>
      <a href="#carousel__slide3"
         class="carousel__prev">Go to previous slide</a>
      <a href="#carousel__slide1"
         class="carousel__next">Go to first slide</a>
    </li>
  </ol>
  <aside class="carousel__navigation">
    <ol class="carousel__navigation-list">
      <li class="carousel__navigation-item">
        <a href="#carousel__slide1"
           class="carousel__navigation-button">Go to slide 1</a>
      </li>
      <li class="carousel__navigation-item">
        <a href="#carousel__slide2"
           class="carousel__navigation-button">Go to slide 2</a>
      </li>
      <li class="carousel__navigation-item">
        <a href="#carousel__slide3"
           class="carousel__navigation-button">Go to slide 3</a>
      </li>
      <li class="carousel__navigation-item">
        <a href="#carousel__slide4"
           class="carousel__navigation-button">Go to slide 4</a>
      </li>
    </ol>
  </aside>
</section>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    circuit court pour le e-commerce des petit commercant !
  </div>
</div>

app/views/shared/_form.html.erb
<div class="new_stores">
  <%= simple_form_for @store do |f| %>
    <%= f.error_notification %>

    <%= f.input :name, placeholder: 'name', maxlength: 25, input_html: { class: 'dasboard_input' }%>

    <%= f.input :presentation, placeholder: 'presentation', input_html: { class: 'dasboard_input' }, maxlength: 50 %>

    <%= f.label :photos, 'Photo' %>
    <%= f.input :photos,as: :file,label: false,input_html: { class: 'divice_sign_in' } %>

    <%= f.button :submit, class: 'device_identification update_store' %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="main_nav">
  <div class="nav_left">
    <a href="/">
      <div class="nav_logo" >
        <h4>Circuit Court</h4>
      </div>
    </a>
  </div>

  <div class="nav_fill">
    <%= simple_form_for :search, url: root_path, method: :get do |f| %>
        <div class="search">
          <input class="searchTerm" type="text" name="search[query]" placeholder="What are you looking for?"/>
          <button type="submit" class="searchButton">
            <i class="fa fa-search"></i>
          </button>
        </div>
    <% end %>
  </div>

  <div class="nav_right">
    <div class="nav-links" id="nav_email"><a>
      <% if trader_signed_in? %>
        <%= current_trader.email %>
      <% elsif user_signed_in? %>
        <%= current_user.email%>
      <% else %>
        <%= link_to "identifiez-vous", new_user_registration_path %>
      <% end %></a>
    </div>

    <div class="nav-links"><a>
      <% if trader_signed_in? %>
        <%= link_to "tableau de bord", dashboard_path %>
      <% else %>
        <%= link_to "Mes achats", user_show_path %>
      <% end %></a>
    </div>

    <div class="nav-links cart">
        <a href="/carts">
          <i class="fa fa-shopping-cart" aria-hidden="true"></i>
        </a>
    </div>
  </div>
</nav>