config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount API::Base, at: "/"
  get 'stripes/new'
  # post 'create_cart', to: 'carts#create', as: "create_cart"
  # get 'show/cart', to: 'carts#show', as: "show"
  get 'indentification/identification'
  devise_for :traders, controllers: { registrations: 'registrations' }
  devise_for :users, controllers: { registrations: 'registrations' }

  root to: 'stores#index'

  get '/orders', to: 'orders#orders', as: :orders
  get '/history', to: 'orders#history', as: :history
  get '/user_show', to: 'orders#user_show', as: :user_show
  get '/dashboard', to: 'orders#dashboard', as: :dashboard
  post '/order_update', to: 'orders#validation_order', as: :validation_order

  get '/trader_show/:store_id', to: 'stores#trader_show', as: :trader_show
  get '/home', to: 'stores#home', as: :home

  resources :stores do
    resources :products, only: %i[index new create]
  end
  resources :products, only: %i[show edit update destroy]

  resources :carts, only: %i[index create destroy]
  patch '/update_cart' => 'carts#update', as: 'update_cart'

  scope '/checkouts' do
    get 'create/:store_id', to: 'checkouts#create_checkout'
    get 'cancel', to: 'checkouts#cancel', as: 'checkout_cancel'
    get 'success/:store_id', to: 'checkouts#success', as: 'checkout_success'
    get 'checkout', to: 'checkouts#checkout', as: 'checkout'
  end

  get '/identification' => 'identifications#identification', as: :identification
  get '/trader_person' => 'identifications#trader_person', as: :trader_person

  get '/trader_edit' => 'identifications#trader_edit', as: :trader_edit
  post '/trader_update' => 'identifications#trader_update', as: :trader_update

  get '/info' => 'identifications#info_stripe', as: :info
  post '/user_info' => 'identifications#user_info', as: :user_info

  get '/trader_info' => 'identifications#trader_info', as: :trader_info
  post '/trader_info_create' => 'identifications#trader_info_create', as: :trader_info_create

  get '/index_sub' => 'subscriptions#index', as: :index_sub
  post '/checkout_sub' => 'subscriptions#checkout_sub', as: :checkout_sub
  post '/webhook' => 'subscriptions#webhook', as: :webhook
  get '/delete_sub' => 'subscriptions#delete_sub', as: :delete_sub
  get '/success' => 'subscriptions#success', as: :success
  get '/checkout_session' => 'subscriptions#checkout_session', as: :checkout_session
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product
  belongs_to :store

  scope :find_order_validation_false, lambda{ |trader| where(store_id: trader.store.id, order_validation: false) }
  scope :find_current_user_orders, lambda{ |user| where(user_id: user.id).order! 'created_at DESC' }
  scope :find_order_validation_true, lambda{ |trader|  where(store_id: trader.store.id, order_validation: true) }
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  def dashboard
    current_trader.store ? @store = Store.find(current_trader.store.id) : ''

    if !current_trader.store.nil?
      @order = Order.find_order_validation_false(current_trader)
      @orders = @order.group_by(&:user_id)
    else
      @orders = []
    end

    @amount = SumOrders.new(@orders).call
  end

  def validation_order
    orders_id = params[:cart].drop(1).flatten
    orders_id.each do |order_id|
      order = Order.find(order_id.to_i)
      order.order_validation
      order.order_validation = true
      order.save
    end

    respond_to do |format|
      format.js { render inline: 'location.reload();' }
    end
  end

  def user_show
    orders = Order.find_current_user_orders(current_user)
    @stores_orders = orders.group_by(&:store_id)
  end

  def history
    @order = Order.find_order_validation_true(current_trader)
    @orders = @order.group_by(&:user_id)

    respond_to do |format|
      format.js { render layout: false } # Add this line to you respond_to block
    end
  end

  def orders
    @order = Order.find_order_validation_false(current_trader)
    @orders = @order.group_by(&:user_id)
    @amount = SumOrders.new(@orders).call

    respond_to do |format|
      format.js { render layout: false } # Add this line to you respond_to block
    end
  end
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/views/orders/_history.html.erb
<div class="container">
  <% @orders.each_with_index do  |store, value| %>
    <div class="cart-store">
      <div class="cart_titel">
        <h2><%= store[1].first.store.name %></h2>
        <h6>Prix</h6>
      </div>
      <% total = 0%>
      <% store[1].each do  |product| %>
      <div class="cart_container">
        <%= cl_image_tag(product.product.photos[0].key, :width => 90, :height => 90) if product.product.photos.present?%>
        <div class="cart-product">
         <p><%= product.product.name %></p>
            <% total += (product.product.price_cents / 100) * product.quantity%>
            <div class="cart_quantity">
              <h6>Qté: <%= product.quantity %></h6>

              <h6>ref: <%= product.product.reference %></h6>

            </div>
        </div>
         <%= product.product.price_cents / 100%> €
      </div>
      <% end %>
      <div class="validation_order_dasboard">
        <!-- <div> -->
          <%= link_to 'commande terminé', validation_order_path(:cart => value), method: :post, remote: true, class: 'red_btn' %>
        <!-- </div> -->
        <h5>Sous-total: <%= total %> €</h5>
      </div>
    </div>
  <% end %>
</div>

app/views/orders/_orders.html.erb
<div class="container">
  <% @orders.each_with_index do  |store, value| %>
    <div class="cart-store">
      <div class="cart_titel">
        <h2><%= store[1].first.store.name %></h2>
        <h6>Prix</h6>
      </div>
      <% total = 0%>
      <% store[1].each do  |product| %>
      <div class="cart_container">
        <%= cl_image_tag(product.product.photos[0].key, :width => 90, :height => 90) if product.product.photos.present?%>
        <div class="cart-product">
         <p><%= product.product.name %></p>
            <% total += (product.product.price_cents / 100) * product.quantity%>
            <div class="cart_quantity">
              <h6>Qté: <%= product.quantity %></h6>

              <h6>ref: <%= product.product.reference %></h6>

            </div>
        </div>
         <%= product.product.price_cents / 100%> €
      </div>
      <% end %>
      <div class="validation_order_dasboard">
        <!-- <div> -->
          <%= link_to 'commande terminé', validation_order_path(:cart => value), method: :post, remote: true, class: 'btn btn-flat' %>
        <!-- </div> -->
        <h5>Sous-total: <%= total %> €</h5>
      </div>
    </div>
  <% end %>
</div>

app/views/orders/dashboard.html.erb
<div class="dashbord_container">
    <ul class="left_bar">
      <% if current_trader.store.nil?%>
        <li><%= link_to "crée la boutique", new_store_path, class: "dasboard_button", remote: true %></li>
      <% else %>
        <li><%= link_to "mise a jours de la boutique", edit_store_path(@store), class: "dasboard_button", remote: true %></li>
      <% end %>

      <% if current_trader.store.nil? ==  false %>
        <li><%= link_to "crée un produit", new_store_product_path(current_trader.store.id), class: "dasboard_button", remote: true %></li>
        <li><%= link_to "mise a jours des produits", trader_show_path(current_trader.store.id), class: "dasboard_button", remote: true %></li>
        <li><%= link_to "commande", orders_path , class: "dasboard_button", remote: true %></li>
        <li><%= link_to "historique des commande", history_path , class: "dasboard_button", remote: true %></li>
      <% end %>
        <li><%= link_to "abonnement", index_sub_path, class: "dasboard_button" %></li>
    </ul>

  <div class="order_container" id="dashboard_partial">
    <h1>Bienvenu dans votre tableau de bord !</h1>
  </div>
</div>

app/views/orders/history.js.erb
a = document.querySelector('#dashboard_partial')
a.innerHTML = "";
a.insertAdjacentHTML('beforeend',"<%= escape_javascript render 'orders/history', locals: { :orders => @orders } %>");

app/views/orders/orders.js.erb
a = document.querySelector('#dashboard_partial')
a.innerHTML = "";
a.insertAdjacentHTML('beforeend',"<%= escape_javascript render 'orders/orders', locals: { :orders => @orders, :amount => @amount } %>");

app/views/orders/subscription.html.erb
    <form id="signup-form">
      <div>
        <input id="email" type="text" placeholder="Email address" required />
      </div>
​
      <button id="email-submit" type="submit">
        <span id="button-text">Sign up</span>
      </button>
    </form>

app/views/orders/user_show.html.erb
<div class="container">
  <% @stores_orders.each do  |store| %>
    <div class="cart-store">
      <div class="cart_titel">
        <h2><%= store[1].first.store.name %></h2>
        <h6>Prix</h6>
      </div>
      <% total = 0%>
      <% store[1].each do  |product| %>
      <div class="cart_container">
        <%= cl_image_tag(product.product.photos[0].key, :width => 180, :height => 180) if product.product.photos.present?%>
        <div class="cart-product">
         <p><%= product.product.name %></p>
            <% total += (product.product.price_cents / 100) * product.quantity%>
        </div>
         <%= product.product.price_cents / 100%> €
      </div>
      <% end %>

      <div class="cart_buy">
        <p>Sous-total:<%= total %> €</p>
      </div>
    </div>
  <% end %>
</div>