config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount API::Base, at: "/"
  get 'stripes/new'
  # post 'create_cart', to: 'carts#create', as: "create_cart"
  # get 'show/cart', to: 'carts#show', as: "show"
  get 'indentification/identification'
  devise_for :traders, controllers: { registrations: 'registrations' }
  devise_for :users, controllers: { registrations: 'registrations' }

  root to: 'stores#index'

  get '/orders', to: 'orders#orders', as: :orders
  get '/history', to: 'orders#history', as: :history
  get '/user_show', to: 'orders#user_show', as: :user_show
  get '/dashboard', to: 'orders#dashboard', as: :dashboard
  post '/order_update', to: 'orders#validation_order', as: :validation_order

  get '/trader_show/:store_id', to: 'stores#trader_show', as: :trader_show
  get '/home', to: 'stores#home', as: :home

  resources :stores do
    resources :products, only: %i[index new create]
  end
  resources :products, only: %i[show edit update destroy]

  resources :carts, only: %i[index create destroy]
  patch '/update_cart' => 'carts#update', as: 'update_cart'

  scope '/checkouts' do
    get 'create/:store_id', to: 'checkouts#create_checkout'
    get 'cancel', to: 'checkouts#cancel', as: 'checkout_cancel'
    get 'success/:store_id', to: 'checkouts#success', as: 'checkout_success'
    get 'checkout', to: 'checkouts#checkout', as: 'checkout'
  end

  get '/identification' => 'identifications#identification', as: :identification
  get '/trader_person' => 'identifications#trader_person', as: :trader_person

  get '/trader_edit' => 'identifications#trader_edit', as: :trader_edit
  post '/trader_update' => 'identifications#trader_update', as: :trader_update

  get '/info' => 'identifications#info_stripe', as: :info
  post '/user_info' => 'identifications#user_info', as: :user_info

  get '/trader_info' => 'identifications#trader_info', as: :trader_info
  post '/trader_info_create' => 'identifications#trader_info_create', as: :trader_info_create

  get '/index_sub' => 'subscriptions#index', as: :index_sub
  post '/checkout_sub' => 'subscriptions#checkout_sub', as: :checkout_sub
  post '/webhook' => 'subscriptions#webhook', as: :webhook
  get '/delete_sub' => 'subscriptions#delete_sub', as: :delete_sub
  get '/success' => 'subscriptions#success', as: :success
  get '/checkout_session' => 'subscriptions#checkout_session', as: :checkout_session
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :store
  has_many_attached :photos
  monetize :price_cents

  searchkick

  def first_product_photo
    photos[0].key
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index; end

  def show
    @product = Product.find(params[:id])
    @photos = @product.photos.includes([:blob])
    @cart = Cart.new
  end

  def edit
    @store = Store.find(current_trader.store.id)
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if product_params['photos'].nil? == false
      @product.photos.each do |photo|
        Cloudinary::Uploader.destroy(photo.key)
      end
    end
    @product.update(product_params)
    redirect_to store_path(@product.store.id)
  end

  def new
    @store = Store.find(current_trader.store.id)
    @product = Product.new
  end

  def create
    product = Product.new(product_params)
    @store = Store.find(params[:store_id])
    product.store = @store
    product.save
    redirect_to store_path(@store)
  end

  def destroy
    product = Product.find(params[:id])
    product.destroy

    # no need for app/views/restaurants/destroy.html.erb
    redirect_to store_path(product.store)
  end

  private

  def product_params
    params.require(:product).permit(:name, :presentation, :price, :stock, :product_characteristic, photos: [])
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper

  def check_stock(product)
    product.stock > 0 ? "En stock" : " stock vide"
  end
end

app/views/products/_edit.html.erb
  <div class = "photos">
     <% @product.photos.each do |photo| %>
            <%= cl_image_tag(photo.key, :width => 250, :height => 200, :class => "photo_product", :id => photo.id) %>
    <% end %>
  </div>
<div class="container">

  <%= simple_form_for [@store, @product], :url => product_path, method: :patch do |f| %>
    <%= f.error_notification %>

    <%= f.input :name, input_html: { class: 'dasboard_input' } %>

    <%= f.input :presentation, input_html: { class: 'dasboard_input' } %>

    <%= f.input :product_characteristic, input_html: { class: 'dasboard_input' } %>

    <%= f.input :stock, input_html: { class: 'dasboard_input' } %>

    <%= f.input :price, input_html: { class: 'dasboard_input' } %>

    <%= f.input :photos, as: :file, input_html: { multiple: true } %>

    <%= f.button :submit, class: "btn btn-flat" %>
    <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
  <% end %>
</div>

app/views/products/_new.html.erb
<div class="new_stores">
  <%= simple_form_for [@store, @product] do |f| %>
    <%= f.error_notification %>

    <%= f.input :name, input_html: { class: 'dasboard_input' } %>

    <%= f.input :presentation, input_html: { class: 'dasboard_input' } %>

    <%= f.input :presentation, input_html: { class: 'dasboard_input' } %>

    <%= f.input :stock , input_html: { class: 'dasboard_input' }%>

    <%= f.input :price , input_html: { class: 'price_input' }%>

    <%= f.input :photos, as: :file, input_html: { multiple: true } %>

    <%= f.button :submit, class: "device_identification update_store" %>
  <% end %>
</div>

app/views/products/delete.html.erb
<h1>Products#delete</h1>
<p>Find me in app/views/products/delete.html.erb</p>

app/views/products/edit.html.erb
<h1>Products#edit</h1>

<div class = "photos">
   <% @product.photos.each do |photo| %>
          <%= cl_image_tag(photo.key, :width => 250, :height => 200, :class => "photo_product", :id => photo.id) %>
  <% end %>
</div>

<%= simple_form_for [@store, @product], :url => product_path, method: :patch do |f| %>
  <%= f.error_notification %>

  <%= f.input :name %>

  <%= f.input :presentation %>

  <%= f.input :stock %>

  <%= f.input :price %>

  <%= f.input :photos, as: :file, input_html: { multiple: true } %>

  <%= f.button :submit, class: "btn-primary" %>
  <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
<% end %>

app/views/products/edit.js.erb
a = document.querySelector('#dashboard_partial')
a.innerHTML = "";
a.insertAdjacentHTML('beforeend',"<%= escape_javascript render 'products/edit', locals: { :product => @product, :store => @store } %>");

app/views/products/index.html.erb
<h1>Products#index</h1>
<p>Find me in app/views/products/index.html.erb</p>

<%= simple_form_for [@store, @product] do |f| %>
  <%= f.error_notification %>

  <%= f.input :name %>

  <%= f.input :presentation %>

  <%= f.input :stock %>

  <%= f.input :price %>

  <%= f.input :photos, as: :file, input_html: { multiple: true } %>

  <%= f.button :submit, class: "btn-primary" %>
  <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
<% end %>

app/views/products/new.html.erb
<h1>Products#new</h1>
<%= simple_form_for [@store, @product] do |f| %>
  <%= f.error_notification %>

  <%= f.input :name %>

  <%= f.input :presentation %>

  <%= f.input :stock %>

  <%= f.input :price %>

  <%= f.input :photos, as: :file, input_html: { multiple: true } %>

  <%= f.button :submit, class: "btn-primary" %>
  <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
<% end %>

app/views/products/new.js.erb
a = document.querySelector('#dashboard_partial')
a.innerHTML = "";
a.insertAdjacentHTML('beforeend',"<%= escape_javascript render 'products/new', locals: { :product => @product, :store => @store } %>");

app/views/products/show.html.erb
<div class="wrapper">
  <div class="page_product">
    <div id= "show_photo">
      <div class = "product_photo">
         <% @photos.each do |photo| %>
                <%= cl_image_tag(photo.key, :width => 40, :height => 40, :class => "photo_product", :id => photo.id) %>
        <% end %>
      </div>
      <div id = "zoom_photo">
          <%= cl_image_tag(@product.first_product_photo) %>
      </div>
    </div>

    <div class="product_data">
      <h1><%= @product.name %></h1>
      <div class="product_data_presentation">
        <%= simple_format(@product.presentation) %>
      </div>
      <%= simple_format(@product.product_characteristic) %>
      <h6 class="product_price size-medium">Prix: <%= @product.price %></h6>
    </div>

    <div class="product_data_recap">
       <h6 class="product_price size-medium">Prix: <%= @product.price %></h6>
       <h6 class="product_stock size-medium"><%= check_stock(@product) %></h6>
      <%= simple_form_for @cart do |f| %>
            <%= f.error_notification %>

            <%= f.hidden_field :product_id, value: "#{@product.id}" %>

            <%= f.hidden_field :store_id, value: "#{@product.store.id}" %>

            <%= f.input :quantity, collection: [1, 2, 3, 4, 5], label: "qantiter :", selected: 1 %>

            <%= f.button :submit,'panier', class: "btGreen btn_prd_data" %>

            <%#= link_to 'Achat', stores_path, :class => 'button' %>
      <% end %>
      <i class="fa fa-lock">Transaction securisée</i>
    </div>
  </div>
</div>